libratbag_references:
  default_settings: &default_settings
    working_directory: ~/libratbag
  build_and_test: &build_and_test
    run:
      name: Build and test
      command: |
        meson build --prefix=/usr
        mesonconf build
        ninja -C build test
  install: &install
    run:
      name: Installing
      command: ninja -C build install
  check_uninstall: &check_uninstall
    run:
      name: Checking if any files are left after uninstall
      command: |
        PREFIX=/root/test_install
        # workaround until https://github.com/mesonbuild/meson/pull/2033 is merged
        # and a new release appears
        git clone https://github.com/whot/meson -b wip/remove-directories-on-uninstall
        ./meson/meson.py build_install --prefix=$PREFIX
        ninja -C build_install install
        ninja -C build_install uninstall
        if [ -d $PREFIX ]
        then
          tree $PREFIX
          exit 1
        fi
  export_logs: &export_logs
    store_artifacts:
      path: ~/libratbag/build/meson-logs


fedora_settings: &fedora_settings
  <<: *default_settings
  steps:
    - run:
        name: Install prerequisites
        command: dnf install -y tree git gcc gcc-c++ meson check-devel libudev-devel libevdev-devel doxygen graphviz valgrind
    - checkout
    - *build_and_test
    - *install
    - *check_uninstall
    - *export_logs


ubuntu_settings: &ubuntu_settings
  <<: *default_settings
  steps:
    - run:
        name: Install prerequisites
        command: |
          apt-get update
          apt-get install -y software-properties-common
          add-apt-repository universe
          apt-get update
          apt-get install -y tree git gcc g++ pkg-config meson check libudev-dev libevdev-dev libsystemd-dev doxygen graphviz valgrind
    - checkout
    - *build_and_test
    - *install
    - *check_uninstall
    - *export_logs


version: 2
jobs:
  fedora_rawhide:
    <<: *fedora_settings
    docker:
      - image: fedora:rawhide
  fedora_latest:
    <<: *fedora_settings
    docker:
      - image: fedora:latest
  ubuntu_17_04:
    <<: *ubuntu_settings
    docker:
      - image: ubuntu:zesty


workflows:
  version: 2
  compile_and_test:
    jobs:
      - fedora_rawhide
      - ubuntu_17_04
      #- fedora_latest
