.TH ratbagd 8 "Apr 13, 2016" ratbagd
.SH NAME
ratbagd \- system daemon to introspect and modify configurable mice
.SH SYNOPSIS
.B ratbagd
.RB [ \-\-verbose[=debug]|\-\-quiet|\-\-version|\-\-help]
.SH DESCRIPTION
.B ratbagd
starts the daemon. It shouldn't be invoked directly;
.B ratbagd
is normally started through DBus activation.
.SH OPTIONS
.TP 8
.B \-\-help
Print help and exit
.TP 8
.B \-\-verbose, \-\-verbose=debug
Enable verbose output, optionally including raw messages as sent and
received from the device. This should be use to debug any issues with the
device.
.TP 8
.B \-\-quiet
Disable any output but error messages.
.TP 8
.B \-\-version
Show the version number.
.SH SEE ALSO
.BR ratbagctl (1)
.SH AUTHORS
.B ratbagd
was written by David Herrmann, Peter Hutterer and Benjamin Tissoires.
.PP
This manual page was written by Stephen Kitt <skitt@debian.org> for
the Debian GNU/Linux system (but may be used by others).
