name: pages

on:
 push:
   branches:
     - master

env:
  UBUNTU_DEP_BUILD: gcc g++ pkg-config systemd libevdev-dev libglib2.0-dev libjson-glib-dev libsystemd-dev libudev-dev libunistring-dev python3-dev python3-evdev python3-pip swig python3-sphinx python3-sphinx-rtd-theme
  PIP_PACKAGES: meson ninja

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pkginstall
        with:
          apt: $UBUNTU_DEP_BUILD
          pip: $PIP_PACKAGES
      - name: Build docs
        uses: ./.github/actions/meson
        with:
          meson_args: -Ddocumentation=true -Dtests=false
          meson_skip_test: yes
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builddir/doc/html/
          allow_empty_commit: true
